# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Kunal Nagar"
email: "knlnagar@gmail.com"
description: "Hi. I'm Kunal. I make the web fast by using JavaScript responsibly."
baseurl: ""
url: "https://kunalnagar.in"

# Variables
twitter_username: "_kunalnagar"
github_username:  "kunalnagar"
google_analytics_key: "UA-51202219-2"

permalink: pretty

# Ignore the projects data type until it's all sorted out
collections:
    projects:
        output: false

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude: []

sass:
    style: compressed
    load_paths:
        - _sass
        - node_modules

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
