title: Kunal Nagar
email: knlnagar@gmail.com
description: Hi. I'm Kunal. Use JavaScript responsibly and help make the web fast.
baseurl: ''
url: 'https://www.kunalnagar.in'

# Ignore the projects data type until it's all sorted out
collections:
  projects:
    output: false

# Build settings
markdown: kramdown
permalink: pretty
destination: ./release
plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - node_modules
  - vendor

sass:
  load_paths:
    - _sass
    - node_modules
  style: compressed
