baseURL = "http://kunalnagar.in/"
languageCode = "en-us"
title = "Kunal Nagar"
theme = "kunalnagar"

googleAnalytics = "UA-51202219-2"
disqusShortname = "kunalnagar"

[params]
	favicon = "favicon.ico"