version: '3.6'

services:
  jekyll:
    image: katiaalamir/ruby-node
    ports:
      - 4000:4000
    volumes:
      - .:/home/katiaalamir.com
    command: >
      bash -c "node -v
      && cd /home/katiaalamir.com
      && bundle config set path 'vendor/bundle'
      && bundle install
      && npm install
      && npm run dev"
