name: Build site

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kunalnagar/ruby-node:alpine
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: bundle_cache
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Setup bundle path to vendor/bundle
        run: bundle config path vendor/bundle
      - name: Install bundle dependencies if not cached
        if: steps.bundle_cache.outputs.cache-hit != 'true'
        run: bundle install --jobs 4 --retry 3
      - name: Install npm dependencies
        run: npm install
      - name: Run linter
        run: npm run pretty-quick
      - name: Create build
        run: npm run build
