name: Continuous Integration

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: Install bundler 2.1.4
        run: sudo gem install bundler -v 2.1.4
      - name: Cache ruby (bundler) dependencies
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Set bundle path to vendor/bundle
        run: bundle config path vendor/bundle
      - name: Install bundle dependencies if not cached
        if: steps.bundle_cache.outputs.cache-hit != 'true'
        run: bundle install --jobs 4 --retry 3
      - name: Install npm dependencies
        run: npm install
      - name: Lint
        run: npm run pretty-quick
      - name: Build
        run: npm run build
      - name: Release (dry-run)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run release -- --dry-run && tree release
      - name: Start server
        run: rm -rf release && npm run dev
      - name: Audit URLs using Lighthouse CI
        uses: treosh/lighthouse-ci-action@v7
        with:
          urls: |
            http://localhost:4000/
            http://localhost:4000/foss
            http://localhost:4000/blog
          budgetPath: ./budget.json
          uploadArtifacts: true
          temporaryPublicStorage: true
