on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7.1'
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install bundler 2.0.2
        run: gem install bundler -v 2.0.2
      - name: Setup bundle path to vendor/bundle
        run: bundle config path vendor/bundle
      - name: Install bundle dependencies
        run: bundle install --jobs 4 --retry 3
      - name: Install npm dependencies
        run: npm install
      - name: Run linter
        run: npm run pretty-quick
      - name: Create build
        run: npm run build
      - name: Release
        if: github.base_ref == 'master' && startsWith(github.ref, 'refs/tags/')
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: release
