on: [push]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7.1'
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Setup bundle path to vendor/bundle
        run: bundle config path vendor/bundle
      - name: Check/Install bundle dependencies
        run: bundle check || bundle install
      - name: Install npm dependencies
        run: npm install
      - name: Run linter
        run: npm run pretty-quick
      - name: Create build
        run: npm run build
      - name: Logging some variables
        run: |
          echo ${{ github.event }}
          echo ${{ github.event_name }}
          echo ${{ github.ref }}
      - name: Release
        if: ${{ github.event == 'release' && startsWith(github.ref, 'refs/tags/') }}
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: release
