name: Release site

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7.1'
      - uses: actions/cache@v2
        id: bundle_cache
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Setup bundle path to vendor/bundle
        run: bundle config path vendor/bundle
      - name: Check if bundle cache is available
        run: bundle check
      - name: Install bundle dependencies if not cached
        if: steps.bundle_cache.outputs.cache-hit != 'true'
        run: bundle install
      - name: Install npm dependencies
        run: npm install
      - name: Run linter
        run: npm run pretty-quick
      - name: Create build
        run: npm run build
      - name: Release
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: release
